default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: secret
  database: secret
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
